;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
; !!!! During platformio.ini debugging, not sure whether the settings are correct


[platformio]
default_envs = T3_V1_6_SX1276

; Select the firmware mode you want to build by uncommenting the corresponding line below. 
; Only one mode should be active at a time.
src_dir = modes/Sensor
;
;src_dir = modes/GateWay

boards_dir = boards

[env]
platform = espressif32@6.12.0
framework = arduino

upload_speed =  460800
monitor_speed = 115200
monitor_filters =
	default
	esp32_exception_decoder
; Add the following, to prevent entering download mode after flashing
monitor_dtr = 0
monitor_rts = 0

lib_deps =
    milesburton/DallasTemperature@^3.11.0
    wollewald/INA226_WE@^1.2.0
    olikraus/U8g2@^2.34.4
    paulstoffregen/OneWire@2.3.7
    jgromes/RadioLib@^7.1.2
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
    rweather/Crypto@^0.4.0
    x385832/Elog@^2.0.17
    yiannisbourkelis/Uptime Library

[esp32_base]
build_flags =
    ${env.build_flags}
    -D ELOG_SD_ENABLE
    -D DISABLE_FS_H_WARNING

[esp32s3_base]
build_flags =
    ${env.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; -UARDUINO_USB_CDC_ON_BOOT
    -DCORE_DEBUG_LEVEL=0

[env:T3_V1_6_SX1276]
board = esp32dev
build_flags = ${esp32_base.build_flags}
    -DT3_V1_6_SX1276

;for testing
[env:native] 
platform = native
framework =
test_build_src = no
build_flags =
    -std=gnu++17
lib_deps =
    throwtheswitch/Unity@^2.6.1
